name: aip

channels:
  - conda-forge
    #- defaults

dependencies:
  - git
  - click
  - pathlib
  - joblib
  - python-dotenv
  - pytest
  - matplotlib
  - pandas
  - pip
  - pip:
    - -r file:/tmp/requirements.txt
  - python=3.11
  #- xeus-python
